In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
import pandas as pd
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df['flower'] = iris.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  flower
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [8]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  flower
0                5.1               3.5                1.4               0.2  setosa
1                4.9               3.0                1.4               0.2  setosa
2                4.7               3.2                1.3               0.2  setosa
3                4.6               3.1                1.5               0.2  setosa
4                5.0               3.6                1.4               0.2  setosa

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [20]:
from sklearn.svm import SVC
model = SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9777777777777777

<h3>Applying K-Fold Cross Validation</h3>

In [21]:
from sklearn.model_selection import cross_val_score

In [23]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [24]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [25]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

<h3>Applying K-Fold Cross Validation but by for loop</h3>

In [30]:
import numpy as np
kernels = ['rbf','linear']
C = [1,10,20]
avg_score = []
for kval in kernels:
    for cval in C:
        cv_score = cross_val_score(SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score.append(np.average(cv_score))
avg_score

[0.9800000000000001,
 0.9800000000000001,
 0.9666666666666668,
 0.9800000000000001,
 0.9733333333333334,
 0.9666666666666666]

<h3>Grid Search CV gives exact same things like above cell</h3>

In [32]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma='auto'),{
    'C' :[1,10,20],
    'kernel' :['rbf','linear']

},cv=5, return_train_score=False)

In [33]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [34]:
clf.cv_results_

{'mean_fit_time': array([0.00159893, 0.00259905, 0.00219846, 0.00162649, 0.00119867,
        0.00119939]),
 'std_fit_time': array([0.00048908, 0.00135646, 0.00074769, 0.00078229, 0.00039916,
        0.00040023]),
 'mean_score_time': array([0.0011992 , 0.00139923, 0.00179882, 0.00059972, 0.00119991,
        0.00079951]),
 'std_score_time': array([0.00039949, 0.00048895, 0.00116617, 0.00048967, 0.00040033,
        0.00039976]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': ar

In [35]:
df = pd.DataFrame(clf.cv_results_)
df.head()

mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score  std_test_score rank_test_score
0       0.001599      0.000489         0.001199  ...         0.980000        0.016330               1
1       0.002599      0.001356         0.001399  ...         0.980000        0.016330               1
2       0.002198      0.000748         0.001799  ...         0.980000        0.016330               1
3       0.001626      0.000782         0.000600  ...         0.973333        0.038873               4
4       0.001199      0.000399         0.001200  ...         0.966667        0.036515               5

[5 rows x 15 columns]

In [36]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [37]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_refit_for_multimetric',
 '_check_scorers_accept_sample_weight',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_html_repr',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_run_sea

In [38]:
clf.best_score_

0.9800000000000001

In [39]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [43]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)

In [44]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [45]:
rs.cv_results_

{'mean_fit_time': array([0.00220079, 0.00179849]),
 'std_fit_time': array([0.00039902, 0.00074874]),
 'mean_score_time': array([0.0013979 , 0.00099936]),
 'std_score_time': array([0.00048946, 0.00063166]),
 'param_kernel': masked_array(data=['rbf', 'rbf'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[10, 1],
              mask=[False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 10}, {'kernel': 'rbf', 'C': 1}],
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.98, 0.98]),
 'std_test_score': array([0.01632993, 0.01632993]),
 'rank_test_score': array([1, 1])}

In [49]:
df = pd.DataFrame(rs.cv_results_)
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       10          rbf             0.98
1        1          rbf             0.98

<h3>How to choose best model</h3>

In [50]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [51]:
sm = SVC(kernel='rbf',C=10,gamma='auto')

In [52]:
sm.fit(x_train,y_train)

SVC(C=10, gamma='auto')

In [53]:
sm.predict(x_test)

array([1, 2, 1, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 2, 2, 0, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 0, 0, 2, 1, 2, 0, 0, 2, 2, 0, 0, 1, 2, 0, 1, 1, 0, 1, 1,
       2])

In [54]:
sm.score(x_test,y_test)

0.9777777777777777

In [56]:
rfc = RandomForestClassifier(n_estimators=5)
rfc.fit(x_train,y_train)

RandomForestClassifier(n_estimators=5)

In [57]:
rfc.predict(x_test)

array([1, 2, 1, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 2, 2, 0, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 0, 0, 2, 1, 2, 0, 0, 2, 2, 0, 0, 1, 2, 0, 1, 1, 0, 1, 1,
       2])

In [59]:
rfc.score(x_test,y_test)

0.9777777777777777

In [61]:
lm = LogisticRegression(solver='liblinear',multi_class='auto',C=5)
lm.fit(x_train,y_train)

C:\Users\star\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\star\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1288: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(


LogisticRegression(C=5, multi_class='auto', solver='liblinear')

In [62]:
model.predict(x_test)

array([1, 2, 1, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 2, 2, 0, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 0, 0, 2, 1, 2, 0, 0, 2, 2, 0, 0, 1, 2, 0, 1, 1, 0, 1, 1,
       2])

In [63]:
model.score(x_test,y_test)

0.9777777777777777